[package]
name = "colorsys"
version = "0.5.5"
description = "Module for convert and transform colors"
authors = ["mz <emgyrz@gmail.com>"]
license = "MIT"
homepage = "https://github.com/emgyrz/colorsys.rs"
repository = "https://github.com/emgyrz/colorsys.rs.git"
keywords = ["colors", "converter", "css", "rgb", "hsl"]
categories = [ "graphics"]
edition = "2018"
readme = "README.md"

[dependencies]
